### ISSUE TITLE
Fatal Exception: android.app.BackgroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by atiqmumtaz507** [3qnexx/nexxPLAY-android#46]
Not allowed to start service Intent

Fatal Exception: android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent { cmp=de.shz/tv.nexx.android.play.system.cache.service.CacheService }: app is in background uid UidRecord{51d79ae u0a452 TPSL idle change:procadj procs:0 seq(25202897,25175540)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1981)
       at android.app.ContextImpl.startService(ContextImpl.java:1927)
       at android.content.ContextWrapper.startService(ContextWrapper.java:834)
       at android.content.ContextWrapper.startService(ContextWrapper.java:834)
       at tv.nexx.android.play.NexxPLAY.startServiceIfItsNotRunning(NexxPLAY.java:213)
       at tv.nexx.android.play.NexxPLAY.onActivityResume(NexxPLAY.java:268)
       at com.prepublic.noz_shz.presentation.page.audioplayer.widget.AudioPlayerWidgetPresenter.onStartOfPlayer(AudioPlayerWidgetPresenter.java:119)
       at com.prepublic.noz_shz.presentation.page.audioplayer.widget.AudioPlayerWidget.setup(AudioPlayerWidget.java:140)
       at com.prepublic.noz_shz.presentation.page.main.MainActivity.setUpAudio(MainActivity.java:132)
       at com.prepublic.noz_shz.presentation.page.main.MainActivity.access$300(MainActivity.java:58)
       at com.prepublic.noz_shz.presentation.page.main.MainActivity$2.run(MainActivity.java:117)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by atiqmumtaz507** [comment]
Version used:  implementation "tv.nexx.android:play:6.3.00-RC3"
