### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by atiqmumtaz507** [3qnexx/nexxPLAY-android#47]
Fatal Exception: java.lang.NullPointerException:
       at java.util.Objects.requireNonNull(Objects.java:220)
       at androidx.media3.common.util.Assertions.checkNotNull(Assertions.java:155)
       at androidx.media3.exoplayer.source.ProgressiveMediaSource$Factory.createMediaSource(ProgressiveMediaSource.java:205)
       at tv.nexx.android.play.player.ExoPlayerAdapter.getRendererBuilder(ExoPlayerAdapter.java:709)
       at tv.nexx.android.play.player.ExoPlayerAdapter.preparePlayer(ExoPlayerAdapter.java:332)
       at tv.nexx.android.play.player.ExoPlayerAdapter.prepare(ExoPlayerAdapter.java:913)
       at tv.nexx.android.play.player.ExoPlayerAdapter.prepare(ExoPlayerAdapter.java:950)
       at tv.nexx.android.play.logic.Sequencer$MediaState.onEntry(Sequencer.java:330)
       at tv.nexx.android.play.logic.Sequencer.doTransition(Sequencer.java:128)
       at tv.nexx.android.play.logic.Sequencer.startMedia(Sequencer.java:64)
       at tv.nexx.android.play.logic.player_logic_state_machine.PlayerLogicStateMachine.startMediaOrGetReady(PlayerLogicStateMachine.java:5595)
       at tv.nexx.android.play.logic.player_logic_state_machine.PlayerLogicStateMachine$31.onValidated(PlayerLogicStateMachine.java:3939)
       at tv.nexx.android.play.logic.MediaManager.checkPayStatusAsync(MediaManager.java:406)
       at tv.nexx.android.play.logic.player_logic_state_machine.PlayerLogicStateMachine.checkPayStatus(PlayerLogicStateMachine.java:3919)
       at tv.nexx.android.play.logic.player_logic_state_machine.PlayerLogicStateMachine.receivedMediaData(PlayerLogicStateMachine.java:3791)
       at tv.nexx.android.play.logic.PlayerLogic.acceptedMediaData(PlayerLogic.java:893)
       at tv.nexx.android.play.logic.PlayerLogic.processMediaData(PlayerLogic.java:887)
       at tv.nexx.android.play.logic.PlayerLogic$3.onMediaDataAvailable(PlayerLogic.java:646)
       at tv.nexx.android.play.logic.MainThreadResponseHandler.onMediaDataAvailable$lambda$1(MainThreadResponseHandler.kt:44)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:240)
       at android.os.Looper.loop(Looper.java:351)
       at android.app.ActivityThread.main(ActivityThread.java:8427)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by atiqmumtaz507** [comment]
version used: implementation "tv.nexx.android:play:6.3.00-RC3"
