### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by atiqmumtaz507** [3qnexx/nexxPLAY-android#48]
Index: 0, Size: 0

Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:437)
       at tv.nexx.android.play.logic.PlayerLogic.processMediaData(PlayerLogic.java:882)
       at tv.nexx.android.play.logic.PlayerLogic$3.onMediaDataAvailable(PlayerLogic.java:646)
       at tv.nexx.android.play.logic.MainThreadResponseHandler.onMediaDataAvailable$lambda$1(MainThreadResponseHandler.kt:44)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by atiqmumtaz507** [comment]
implementation "tv.nexx.android:play:6.3.00-RC3"
